name: slack-gpt
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- _ipython_minor_entry_point=8.7.0
- appnope=0.1.3
- asttokens=2.2.0
- async_generator=1.10
- attrs=22.1.0
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.4
- brotlipy=0.7.0
- bzip2=1.0.8
- ca-certificates=2022.9.24
- certifi=2022.9.24
- cffi=1.15.1
- click=8.1.3
- cryptography=38.0.4
- decorator=5.1.1
- executing=1.2.0
- h11=0.14.0
- idna=3.4
- ipython=8.7.0
- jedi=0.18.2
- libffi=3.4.2
- libsqlite=3.40.0
- libzlib=1.2.13
- matplotlib-inline=0.1.6
- ncurses=6.3
- openssl=3.0.7
- outcome=1.2.0
- parso=0.8.3
- pexpect=4.8.0
- pickleshare=0.7.5
- pip=22.3.1
- prompt-toolkit=3.0.33
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pycparser=2.21
- pygments=2.13.0
- pyopenssl=22.1.0
- pysocks=1.7.1
- python=3.11.0
- python-dotenv=0.21.0
- python_abi=3.11
- readline=8.1.2
- selenium=4.7.0
- setuptools=65.5.1
- six=1.16.0
- slack-sdk=3.19.5
- slack_sdk=3.19.5
- sniffio=1.3.0
- sortedcontainers=2.4.0
- sqlite=3.40.0
- stack_data=0.6.2
- tk=8.6.12
- traitlets=5.6.0
- trio=0.22.0
- trio-websocket=0.9.2
- typing_extensions=4.4.0
- tzdata=2022g
- urllib3=1.26.13
- webdriver-manager=3.8.5
- wcwidth=0.2.5
- wheel=0.38.4
- wsproto=1.2.0
- xz=5.2.6
